[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags = 
    -D BEARSSL_SSL_BASIC
    -D ARDUINOJSON_ENABLE_STD_STRING=0
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
